/* spells used in Merc */

/*
 * Spell functions.
 * Defined in magic.c.
 */
DECLARE_SPELL_FUN(	spell_null		);
DECLARE_SPELL_FUN(	spell_haven		);
DECLARE_SPELL_FUN(	spell_create_camp	);
DECLARE_SPELL_FUN(	spell_roaring_winds	);
DECLARE_SPELL_FUN(	spell_sanctuary		);
DECLARE_SPELL_FUN(	spell_water_blast	);
DECLARE_SPELL_FUN(	spell_temporal_gust	);
DECLARE_SPELL_FUN(	spell_armor		);
DECLARE_SPELL_FUN(	spell_courage		);
DECLARE_SPELL_FUN(	spell_breathe_underwater);
DECLARE_SPELL_FUN(	spell_blinding_light	);
DECLARE_SPELL_FUN(	spell_sand_blast	);
DECLARE_SPELL_FUN(	spell_chain_lightning	);
DECLARE_SPELL_FUN(      spell_calm_spirit	);
DECLARE_SPELL_FUN(      spell_remove_aura	);
DECLARE_SPELL_FUN(	spell_mind_blast	);
DECLARE_SPELL_FUN(	spell_pain_touch	);
DECLARE_SPELL_FUN(      spell_maelstrom   	);
DECLARE_SPELL_FUN(	spell_control_mind	);
DECLARE_SPELL_FUN(	spell_desert_fist	);
DECLARE_SPELL_FUN(	spell_arrows_of_fire	);
DECLARE_SPELL_FUN(	spell_continual_light	);
DECLARE_SPELL_FUN(	spell_create_ration	);
DECLARE_SPELL_FUN(	spell_create_major_portal );
DECLARE_SPELL_FUN(	spell_create_minor_portal );
DECLARE_SPELL_FUN(	spell_find_spring	);
DECLARE_SPELL_FUN(	spell_create_water	);
DECLARE_SPELL_FUN(	spell_remove_blindness	);
DECLARE_SPELL_FUN(	spell_cure_critical	);
DECLARE_SPELL_FUN(      spell_cure_disease	);
DECLARE_SPELL_FUN(	spell_cure_light	);
DECLARE_SPELL_FUN(	spell_remove_poison	);
DECLARE_SPELL_FUN(	spell_cure_serious	);
DECLARE_SPELL_FUN(	spell_curse		);
DECLARE_SPELL_FUN(	spell_detect_world	);
DECLARE_SPELL_FUN(	spell_detect_hidden	);
DECLARE_SPELL_FUN(	spell_senses		);
DECLARE_SPELL_FUN(	spell_detect_shadowform	);
DECLARE_SPELL_FUN(	spell_detect_magic	);
DECLARE_SPELL_FUN(	spell_detect_poison	);
DECLARE_SPELL_FUN(	spell_dispel_evil	);
DECLARE_SPELL_FUN(	spell_boulder_toss	);
DECLARE_SPELL_FUN(	spell_extraction	);
DECLARE_SPELL_FUN(	spell_dispel_magic	);
DECLARE_SPELL_FUN(	spell_pyrotechnics	);
DECLARE_SPELL_FUN(	spell_nightmare_cloud	);
DECLARE_SPELL_FUN(	spell_dream_dust	);
DECLARE_SPELL_FUN(	spell_restless_sleep	);
DECLARE_SPELL_FUN(	spell_enchant_armor	);
DECLARE_SPELL_FUN(	spell_enchant_weapon	);
DECLARE_SPELL_FUN(	spell_energy_drain	);
DECLARE_SPELL_FUN(	spell_faerie_fire	);
DECLARE_SPELL_FUN(	spell_reveal		);
DECLARE_SPELL_FUN(	spell_sunfire		);
DECLARE_SPELL_FUN(	spell_sand_storm	);
DECLARE_SPELL_FUN(	spell_fly		);
DECLARE_SPELL_FUN(	spell_levitate		);
DECLARE_SPELL_FUN(      spell_frenzy		);
DECLARE_SPELL_FUN(	spell_planar_travel	);
DECLARE_SPELL_FUN(	spell_empower		);
DECLARE_SPELL_FUN(	spell_godfire		);
DECLARE_SPELL_FUN(	spell_disintigrate	);
DECLARE_SPELL_FUN(      spell_haste		);
DECLARE_SPELL_FUN(      spell_slow		);
DECLARE_SPELL_FUN(	spell_heal		);
DECLARE_SPELL_FUN(      spell_holy_word		);
DECLARE_SPELL_FUN(	spell_identify		);
DECLARE_SPELL_FUN(      spell_illuminate    	);
DECLARE_SPELL_FUN(	spell_infravision	);
DECLARE_SPELL_FUN(	spell_shadowform	);
DECLARE_SPELL_FUN(	spell_locate_object	);
DECLARE_SPELL_FUN(	spell_ice_shards	);
DECLARE_SPELL_FUN(	spell_sand_jambiya	);
DECLARE_SPELL_FUN(	spell_flying_dagger	);
DECLARE_SPELL_FUN(      spell_mass_healing	);
DECLARE_SPELL_FUN(	spell_group_healing	);
DECLARE_SPELL_FUN(	spell_mass_shadowform	);
DECLARE_SPELL_FUN(	spell_dimension_walk	);
DECLARE_SPELL_FUN(      spell_plague		);
DECLARE_SPELL_FUN(	spell_poison		);
DECLARE_SPELL_FUN(	spell_protection	);
DECLARE_SPELL_FUN(	spell_element_protection);
DECLARE_SPELL_FUN(	spell_refresh		);
DECLARE_SPELL_FUN(	spell_remove_curse	);
DECLARE_SPELL_FUN(	spell_circle_of_protection	);
DECLARE_SPELL_FUN(	spell_shatter		);
DECLARE_SPELL_FUN(	spell_wind_vortex	);
DECLARE_SPELL_FUN(	spell_protection_from_fire);
DECLARE_SPELL_FUN(	spell_protection_from_water);
DECLARE_SPELL_FUN(	spell_protection_from_wind);
DECLARE_SPELL_FUN(	spell_protection_from_earth);
DECLARE_SPELL_FUN(	spell_protection_from_spirit);
DECLARE_SPELL_FUN(	spell_fire_shield	);
DECLARE_SPELL_FUN(	spell_earth_shield	);
DECLARE_SPELL_FUN(	spell_water_shield	);
DECLARE_SPELL_FUN(	spell_wind_shield	);
DECLARE_SPELL_FUN(	spell_spirit_shield	);
DECLARE_SPELL_FUN(	spell_sleep		);
DECLARE_SPELL_FUN(	spell_stone_skin	);
DECLARE_SPELL_FUN(	spell_summon		);
DECLARE_SPELL_FUN(	spell_tongues		);
DECLARE_SPELL_FUN(	spell_teleport		);
DECLARE_SPELL_FUN(	spell_weaken		);
DECLARE_SPELL_FUN(	spell_whispering_wind	);
DECLARE_SPELL_FUN(	spell_spirit_talk	);
DECLARE_SPELL_FUN(	spell_warning_web	);
DECLARE_SPELL_FUN(	spell_return_to_safety	);
DECLARE_SPELL_FUN(	spell_acid_breath	);
DECLARE_SPELL_FUN(	spell_fire_breath	);
DECLARE_SPELL_FUN(	spell_gas_breath	);
DECLARE_SPELL_FUN(	spell_lightning_breath	);
DECLARE_SPELL_FUN(      spell_entangle          );
DECLARE_SPELL_FUN(	spell_minor_sacrifice	);
DECLARE_SPELL_FUN(	spell_sacrifice		);
DECLARE_SPELL_FUN(	spell_major_sacrifice	);
DECLARE_SPELL_FUN(  spell_rebuke        );

